### ISSUE TITLE
error installing tirdad

### ISSUE THREAD

**Issue by anon-lestat** [0xsirus/tirdad#12]
i compiled tirdad with make and did "insmod module/tirdad.ko"
It said Operation not permitted. I Typed the command dmesg and it says: FATAL: Can't find kallsyms_lookup_name.

**Comment by 0xsirus** [comment]
What's your kernel version and distribution? Did you run it using root user?
Please post the output of `uname -a`.

**Comment by anon-lestat** [comment]
Linux host 5.4.92_1 #1 SMP PREEMPT 1612047255 x86_64 GNU/Linux. 
Its a custom kernel. If you want i could post the config file. Its based on whonix Hardened-kernel, i made it with help from madaidan.

**Comment by anon-lestat** [comment]
and distro is void linux

**Comment by anon-lestat** [comment]
i used root ofc.

**Comment by anon-lestat** [comment]
i was thinking maybe its because of kptr_restrict=2?

**Comment by 0xsirus** [comment]
Your kernel version is supported and `kptr_restrict` shouldn't be able to limit tirdad functionality as tirdad extracts the symbol addresses using a low-level kernel feature from inside the kernel that normally is not affected by that `sysctl` option. So it must be something with the way you have configured and compiled your kernel. However finding out which config option is the culprit can be a daunting task. And by the way I hadn't heard there's a problem getting tirdad to work on Linux-Hardened (I haven't tested though). But since maintaining an out-of-tree kernel module even for the official kernel and distributions is challenging enough given the magnitude of low-level changes in kernel code, I only focus on keeping it working on the official releases. You can check with madadian and see whether they can compile the module on Linux-Hardened. Specially check whether `CONFIG_KPROBES` is enabled in your config file or not.

**Comment by anon-lestat** [comment]
kprobes are disabled. (https://www.whonix.org/wiki/Hardened-kernel)

**Comment by anon-lestat** [comment]
i guess thats the culprit yeah?

**Comment by 0xsirus** [comment]
Yes, tirdad uses kprobes. Unfortunately some of security restrictions also restrict some necessary security measures. Some of the options that have been disabled in the hardened kernel probably shouldn't be disabled at all.
