### ISSUE TITLE
Tirdad as a Static Kernel Module without CONFIG_KPROBES and CONFIG_KALLSYMS

### ISSUE THREAD

**Issue by oven8Mitts** [0xsirus/tirdad#16]
Hello,

I am working on building Tirdad directly into a custom kernel of mine. This kernel deliberately lacks `CONFIG_KPROBES=n`and `CONFIG_KALLSYMS=n`, so the default code to specify `tcp_secure_seq_adr` will not function.

Since the module is being built statically, using `CONFIG_TIRDAD=y`, I am hoping to take advantage of compile time linking to remove the requirements for KPROBES and the kallsyms_lookup_name() call. 

I've tried a couple things thus far, and I seem to be unable to nail down why my kernel is crashing, looking for the proper way to do this:

This causes a crash without outputting logs to the boot console:

```
#include <net/secure_seq.h>
extern u32 secure_tcp_seq(__be32 saddr, __be32 daddr, __be16 sport, __be16 dport); //force compiler to link this
...
int hook_init(void){
...
tcp_secure_seq_adr = (u64)&secure_tcp_seq; //attempt to allocate the address normally rather than by using kprobe and kallsym_lookup_name?
...
```

I've also tried calling `kallsyms_lookup_name("secure_tcp_seq");` directly, but this causes another crash, albeit this one is a panic due to being unable to find any boot block device (strange..). I've tried a few things  to mess with the SYMBOL_LOOKUP() function and I could not get it to work either.

Surely I am doing this incorrectly, I'm not that good at understanding C so far. 

Linux 6.3.10 with Linux-Hardened patch
Clang LLVM 17 with Full LTO and CFI

**Comment by 0xsirus** [comment]
Hello,

Kernel developers have already made it challenging enough to get symbol addresses. If you don't want to use kprobe, there's no other way that I know of to cleanly get symbol addresses dynamically. That said, since you try to do things at compile time, you can directly write your code in `secure_tcp_seq()` instead of writing another function and hook the original one and do all those tricky hacks that you see in the module. Some time ago I had prepared a patch to add tirdad to the kernel core in a controllable way so that the user can choose when they want to use the original functionality and when the modified one through a sysctl option. I sent the patch to the Linux developers but since in their opinion the ISN issue is not a major problem they refused to apply the patch system wide. The patch is here:
[[PATCH] Clock-independent TCP ISN generation](https://lore.kernel.org/netdev/70c41960-6d14-3943-31ca-75598ad3d2d7@gmail.com/)
 
Since it's been a while I'm not sure whether the functionality of the code above is exactly the same as `secure_tcp_seq_hooked` in the last version of the module but you can use it to get an idea on how to build tirdad in your custom kernel.

**Comment by 0xsirus** [comment]
For some reason, kernel developers decided to define a 6th version for a TCP payload in IPv6 packets while it's the same TCP, it's not a separate protocol. So they have a different function that basically reads 4 bytes of source and destination addresses of the IPv6 socket buffer and the rest of the work is similar. They could do everything in the same function. Another function was not necessary.

But technically yes, given the way they have defined and use TCP6, we will need a separate patch for `secure_tcpv6_seq()`. Currently IPv6 is still less used than IPv4 specially in TOR. With the growing IPv6 usage, I might add support for it in near future. But for now it's not a big concern.
