### ISSUE TITLE
Please document proper in-tree build or update linux-hardened pull request

### ISSUE THREAD

**Issue by KyunLFA** [0xsirus/tirdad#19]
Compiling a kernel from scratch is a tedious process on anything but high end hardware and it would be nice to be able to easily discern the proper way to compile (your upstream) Tirdad inside the Linux kernel tree, specially to compile statically with =y, since the approach done on your pull request to linux-hardened (which would be your blessed in-tree implementation) differs a lot from what a layman (like me) might be able to discern from this repo's tirdad.c, which if I understand correctly is supposed to hot-patch the working kernel instead of being used as the default TCP ISN generator.

Alternatively, simply updating your pull request to linux-hardened featuring your latest changes would also suffice for me personally, though admittedly not as useful for other people who may wish to use their own kernel flavor and want to build Tirdad in-tree.

Thanks for your work and I hope to see this gain more users and maybe get it to upstream Linux eventually.

Cheers!

**Comment by 0xsirus** [comment]
I had sent working patches to both main Linux development repository and to linux-hardened as you have seen. But the maintainers did not cooperate to add the code to the baseline kernel and I basically wasted my time, twice. The problem is kernel has a dynamic nature. If we want to update an old standard patch, it usually needs re-writing some parts of the patch, recompiling, debugging and testing to make sure everything works fine with the new kernels. The code that I had sent to netdev mailing list, was a patch file to add the necessary changes to the Linux kernel which gave the users the option to either use my generator or the default Linux generator at their own discretion using a sysctl option. It was a nice way to create a balance between the legacy and the new code which aimed to address a subtle privacy issue in specific scenarios like when the system is connected to anonymity networks. The kernel developers did not accept the patch because in their opinion the issue was not serious enough to warrant adding new code. 
Similarly, I didn't get a timely response from linux-hardened as well. 
Yes, ideally this patch should be incorporated into the Linux core but I will not spend more time on preparing another standard patch when there is no guarantee in the first place that it will be accepted.

**Comment by KyunLFA** [comment]
Fair enough, I understand sometimes people are uncooperative with our goals specially regarding privacy.

Sorry if I wasted your time or seemed imposing on the linux-hardened/upstream front.

On the other hand, though, I would still like to know the best placement for the Tirdad.c inside the kernel tree given I make a Kconfig and Makefile correctly for it just to get it working without DKMS (laugh).

Thank you again for your earnest work.

**Comment by 0xsirus** [comment]
If we want to add this functionality to kernel, the related functions can be modified directly which are `secure_tcp_seq()` and `secure_tcpv6_seq()`. So you don't necessarily need to add a C file to kernel. And even if you do, it will definitely look different from tirdad.c in this repository because basically we will not need the hooking functionality there; it will look significantly simpler. So if you're familiar with system-level C coding, you should be able to port current tirdad's functionality directly to 'net/core/secure_seq.c'. 
I can write a patch and maintain it in this repository, but the problem is I will have to address the necessary changes that will inevitably exist with future versions of the kernel if the patch is not accepted officially.
Dose the pull request that I sent to linux-hardened in 2020, help you figure out how to do it on your own? Take a look at the commits that I've done in that pull request. Specially this one: https://github.com/0xsirus/linux-hardened/commit/16be9f350769ed3d461a5a8385c53bd6e5880fdf

**Comment by adrelanos** [comment]
A Linux kernel upstream patch has been submitted:

[[PATCH] net: add option for using randomized TCP ISNs](https://lore.kernel.org/netdev/20241007212735.460dc0eb@kf-ir16/T/#u)

by @ArrayBolt3

**Comment by adrelanos** [comment]
protocol vulnerability bug report:

[[tcpm] Security concerns with relative timestamp exposure through TCP ISNs](https://mailarchive.ietf.org/arch/msg/tcpm/FzXQv-QmlQyMi-hbvGpg9uCB5Zs/)

by @ArrayBolt3
