### ISSUE TITLE
Security review of tirdad source code

### ISSUE THREAD

**Issue by ArrayBolt3** [0xsirus/tirdad#23]
Hello! I'm a contributor to the Kicksecure and Whonix projects, and as part of my work I did a security review on the code of tirdad. I found some potential bugs and things that could be fixed up a bit, and wanted to share them here in case you found them useful. Items are listed in order from most worrying to least worrying.

## Safety of `get_secret`

```c
siphash_key_t *get_secret(void){
  u32 temp;

  temp = *((u32*)(&seq_secret.key[0]));
  temp>>=8;
  last_secret.key[0] += temp;
  temp = *((u32*)(&seq_secret.key[1]));
  temp>>=8;
  last_secret.key[1] += temp;

  return &last_secret;
}
```

Is there a particular reason that tirdad incrementally modifies a previously generated SipHash key rather than just generating a new one on every iteration? Given that this code modifies the internal state of the CSPRNG, this code is worrying since in theory an attacker could derive information about the CSPRNG by looking at TCP ISNs unless this algorithm is proven secure. The Linux kernel's siphash documentation (`linux/Documentation/security/siphash.rst`) states that "[k]eys should always be generated from a cryptographically secure source of random numbers...", and since this code randomizes the created ISN every time it's called it seems easier and safer to just generate a new key using `get_random_bytes` every time this is called.

## Manual patching with `install_hook_on`, `store_p_bits`, and `recover_one`

I'm not an expert in Linux page table manipulation, so I can't tell how these functions work, but they definitely are doing a *lot* of complex, low-level work. Couldn't the kernel live patching API be used here instead? That would make things a lot simpler and potentially safer.

## Potentially dangerous use of `memset` in `hook_init`

```c
	seqv4.adr = 0;
	seqv6.adr = 0;

	memset(&seq_secret.key,0,AGGREGATE_KEY_SIZE);
```

Earlier in the module `AGGREGATE_KEY_SIZE` is defined to be `16`.

This `memset` call assumes that `siphash_key_t` will only ever contain a `key` field, and that it will always be exactly 16 bytes long (two u64 values). As of Linux 6.1 both of these are true, but neither of them are guaranteed, and if either of them change, this code will very likely do things it wasn't intended to (partial initialization of memory or buffer overflow). Would `memset(&seq_secret, 0, sizeof(siphash_key_t));` work here instead?

## Potentially dangerous use of `strcat` in `_s_out`

```c
void _s_out(u8 err, char *fmt, ...){
    va_list argp;
    char msg_fmt[255];


    if (err){
    strcpy(msg_fmt,CRED"[!] TIRDAD: "CNORM);
    }else{
    strcpy(msg_fmt,CGREEN"[-] TIRDAD: "CNORM);
    }   
    strcat(msg_fmt,fmt);
    strcat(msg_fmt,"\n");
    va_start(argp,fmt);
    vprintk(msg_fmt,argp);
    va_end(argp);
}
```

Right now there's nothing in tirdad that makes this a problem, but `_s_out` assumes that whatever is passed into the `fmt` algorithm will fit in however much room there is left in `msg_fmt` after the addition of the tirdad "marker" at the start. The array is fixed-size and the `fmt` variable could be of any arbitrary length, so if a really big string is passed in (one dynamically generated, for instance), this will buffer overflow. Using `strncat` instead may resolve the problem.

## Confusing C macro `HANDLER`

```c
#define SYMBOL_LOOKUP(s) (((u64 (*)(const char *))(kasln_adr))(s))
#define HANDLER(t,l,ret,...) t l ## h_hk(struct kprobe * kp, struct pt_regs * r\
          __VA_OPT__(,) __VA_ARGS__){\
            ret;\
          }

HANDLER(int,pre,return 0)
HANDLER(void,post,return,unsigned long flags)
```

This is not exactly easy to read, and it's actually shorter to write the equivalent expanded code manually:

```
int preh_hk(struct kprobe *kp, struct pt_regs *r ) { return 0; }
void posth_hk(struct kprobe *kp, struct pt_regs *r, unsigned long flags) { return; }
```

## Ambiguous errno use

```c
  if (!seqv4.adr || !seqv6.adr){
    _s_out(1,"FATAL: Name lookup failed.");
    return -1; //EPERM but we use it as a generic error number
  }
```

If this return value is used as an errno, it seems to me that using descriptive errno values would be worthwhile. Otherwise, I don't think the comment about EPERM is needed, it slightly confused me while reading the code.

## Weak randomness check after initial `get_random_bytes` call

```c
  get_random_bytes(&seq_secret.key,AGGREGATE_KEY_SIZE);

  for (i=0;i<32;i++){
    if ( *( ((u8*)(&seq_secret.key)) + i ) !=0)
      break;
  }
```

This is a good sanity check, but if we're checking the output of `get_random_bytes` anyway it might be worthwhile to make sure it didn't return a whole bunch of identical non-zero bytes.

## Strict aliasing violation with type punning

This isn't really a problem since Linux is built with `-fno-strict-aliasing`, but there's a lot of places in the code that get a pointer to a variable, cast it to an incompatible pointer type, and then dereference it. Generally unions are preferable when this kind of thing is necessary. Not sure if it's worth it to rewrite those parts, but I thought I'd mention it at least.

That's what I found looking through it. Thanks for making this kernel module, it looks really useful. If I find the time, I'll try porting it to use kernel live patching and see if it still works that way.

**Comment by 0xsirus** [comment]
Greetings,

> Is there a particular reason that tirdad incrementally modifies a previously generated SipHash key rather than just generating a new one 

Incrementing is not necessary. What matters it that each time we should get a new pseudo random number that does not follow any predictable pattern. I didn't want to exhaust kernel's random number pool so I only invoked the function once. Note that it's better to call `wait_for_random_bytes()` before calling `get_random_bytes()` but since network ISN generator is not a place we want to wait and I don't use the function more than one time I assumed it would be ok to directly call `get_random_bytes()`. Now  if you prefer to get a new 32-byte pack of random bits per each new connection, as long as `get_random_bytes()` doesn't fail, it's fine with me. 

> Couldn't the kernel live patching API be used here instead? 

This is a great question. At the time of writing this code I wasn't aware of a straightforward and reliable way and I implemented a hacky solution which bypasses kernel security measures at the lowest level to install the hook. If you know a better way to do this, I would be happy to use that. I saw your pull requests and I'll check them as soon as I find some free time.

> Potentially dangerous use of strcat in _s_out

The way the function is used in the module, does not raise any security concern. `_s_out()` is not supposed to called by external code.

> Confusing C macro HANDLER
> Strict aliasing violation with type punning

Hacky ways... Still, no security issues in the module as long as it's compiled for amd64 architecture and the user doesn't change stuff.


> Ambiguous errno use

`-1` is generally used for EPERM in other places. I clarified it's not the case in this module.

> Weak randomness check after initial get_random_bytes call

There are definitely better ways to check the return value but anything more than making sure that the random number didn't completely fail is an overkill here. While it's in theory possible for the function to return 32 consecutive zeros, the chance is so low that if it happens, I decided it's better to abort and have the user install the module again. Again, no concern in this scenario. 

Overall, you made good points. I changed the code a couple of times since the time I published it initially but have been using the exact same strategy. At the time,  just wanted to get the job done using a secure and effective implementation. The goal was achieved but the code would definitely benefit from a careful review. So thank you for providing this feedback. I'll write another update after I read your PRs.

**Comment by ArrayBolt3** [comment]
Thanks for taking a look! On the topic of using `get_random_bytes`, I don't think it's too much of a worry that kernel entropy could be exhausted (at least not on recent kernels, maybe this is a bigger problem than I realize on older ones). For instance a pull request I made against Qubes OS, I had originally used a similar strategy to yours for generating pseudorandom numbers cheaply, using the ISAAC CSPRNG. I was requested by a Qubes OS dev to just use `getrandom()` (which I believe is essentially the usermode equivalent of `get_random_bytes`) since entropy drain wasn't a concern (https://github.com/QubesOS/qubes-gui-daemon/pull/149#issuecomment-2389986254). In my testing `get_random_bytes` always returned a random value on every ISN generation.

**Comment by 0xsirus** [comment]
I applied new changes by moving the original code to the legacy folder (for my future reference and in case someone wants to use it for any reason) and adding the new implementation in the main module directory. For the new code I used the file in kicksecure repo with some minor modifications. 
Just leaving this note here and closing the issue:

_Be careful of frequent invocations of `get_random_bytes()`._

Cheers,
Sirus
