### ISSUE TITLE
[!] Couldn't resolve address for secure_tcp_seq from /proc/kallsyms

### ISSUE THREAD

**Issue by n1m1** [0xsirus/tirdad#3]
As per title.

I cloned the module and compiled it. When I run 

> ./load start

as root, I get 

> [!] Couldn't resolve address for secure_tcp_seq from /proc/kallsyms

OS: Raspian Buster.

**Comment by adrelanos** [comment]
as root (or with sudo):

    sysctl -n kernel.kptr_restrict

If it shows `2`, then that is the culprit. If that is the cause, needs to be temporarily set to `1`.

    sysctl -w kernel.kptr_restrict=1

Can be reset to original after loading tirdad.

    sysctl -w kernel.kptr_restrict=2

I've created a bash based loader which automates that.

https://github.com/Whonix/tirdad/blob/master/loader

However, that loader uses `modprobe` rather than `insmod` so the module needs to be properly installed (which might be a Linux distribution specific challenge).

See also my pull which includes that: https://github.com/0xsirus/tirdad/pull/2

**Comment by n1m1** [comment]
Yes, the culprit was kernel.kptr_restrict=2 . Fixed.
